"""
STEP 6: Retrain YOLOv8 on Expanded Dataset
============================================
Merges the original training data with pseudo-labeled data,
then retrains YOLOv8s for improved performance.

Input:
  dataset/split/train/              <- original train data
  dataset/pseudo_labeled/           <- pseudo-labeled data from Step 5
  outputs/train_v1/weights/best.pt  <- model from Step 4
Output:
  outputs/train_v2/                 <- retrained model
  dataset/data_expanded.yaml        <- updated dataset config
"""

import sys
import shutil
from pathlib import Path

try:
    from ultralytics import YOLO
except ImportError:
    print("[FATAL] ultralytics not installed.")
    sys.exit(1)

import torch

# ──────────────────────────────────────────────────────────────
# CONFIGURATION
# ──────────────────────────────────────────────────────────────

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent

# Source data
ORIG_TRAIN_IMG = PROJECT_ROOT / "dataset" / "split" / "train" / "images"
ORIG_TRAIN_LBL = PROJECT_ROOT / "dataset" / "split" / "train" / "labels"
PSEUDO_IMG = PROJECT_ROOT / "dataset" / "pseudo_labeled" / "images"
PSEUDO_LBL = PROJECT_ROOT / "dataset" / "pseudo_labeled" / "labels"

# Expanded training set
EXPANDED_IMG = PROJECT_ROOT / "dataset" / "split" / "train_expanded" / "images"
EXPANDED_LBL = PROJECT_ROOT / "dataset" / "split" / "train_expanded" / "labels"

# Validation stays the same
VAL_IMG = PROJECT_ROOT / "dataset" / "split" / "val" / "images"
TEST_IMG = PROJECT_ROOT / "dataset" / "split" / "test" / "images"

# Model
V1_MODEL = PROJECT_ROOT / "outputs" / "train_v1" / "weights" / "best.pt"
OUTPUT_DIR = PROJECT_ROOT / "outputs"
RUN_NAME = "train_v2"
DATA_YAML_EXPANDED = PROJECT_ROOT / "dataset" / "data_expanded.yaml"

# Training config
IMG_SIZE = 640
EPOCHS = 100
BATCH_SIZE = 16
OPTIMIZER = "AdamW"
LR0 = 0.0005         # Lower LR for fine-tuning
LRF = 0.01
PATIENCE = 15
WORKERS = 4
DEVICE = "0" if torch.cuda.is_available() else "cpu"

CLASS_NAMES = ["PP", "HDPE", "PET", "Rigid"]
IMG_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp"}


def main():
    print("=" * 60)
    print("  STEP 6: Retrain on Expanded Dataset")
    print("=" * 60)

    # Check prerequisites
    if not V1_MODEL.exists():
        print(f"[FATAL] V1 model not found: {V1_MODEL}")
        print(f"        Run step4_yolo_train.py first.")
        sys.exit(1)

    # Create expanded dataset by merging original + pseudo-labeled
    print(f"\n  Merging original training data + pseudo-labeled data...")

    if EXPANDED_IMG.exists():
        shutil.rmtree(EXPANDED_IMG.parent)
    EXPANDED_IMG.mkdir(parents=True, exist_ok=True)
    EXPANDED_LBL.mkdir(parents=True, exist_ok=True)

    # Copy original training data
    orig_count = 0
    for img in ORIG_TRAIN_IMG.iterdir():
        if img.suffix.lower() in IMG_EXTENSIONS:
            shutil.copy2(img, EXPANDED_IMG / img.name)
            lbl = ORIG_TRAIN_LBL / (img.stem + ".txt")
            if lbl.exists():
                shutil.copy2(lbl, EXPANDED_LBL / lbl.name)
                orig_count += 1

    # Copy pseudo-labeled data
    pseudo_count = 0
    if PSEUDO_IMG.exists() and PSEUDO_LBL.exists():
        for img in PSEUDO_IMG.iterdir():
            if img.suffix.lower() in IMG_EXTENSIONS:
                shutil.copy2(img, EXPANDED_IMG / img.name)
                lbl = PSEUDO_LBL / (img.stem + ".txt")
                if lbl.exists():
                    shutil.copy2(lbl, EXPANDED_LBL / lbl.name)
                    pseudo_count += 1

    total = orig_count + pseudo_count
    print(f"  Original images:     {orig_count}")
    print(f"  Pseudo-labeled:      {pseudo_count}")
    print(f"  Total expanded set:  {total}")

    # Write expanded data.yaml
    split_dir = PROJECT_ROOT / "dataset" / "split"
    content = f"""# YOLOv8 Expanded Dataset Configuration
# Auto-generated by step6_retrain.py

path: {split_dir.resolve()}
train: {EXPANDED_IMG.resolve()}
val: {VAL_IMG.resolve()}
test: {TEST_IMG.resolve()}

nc: 4
names: [{', '.join(f"'{n}'" for n in CLASS_NAMES)}]
"""
    with open(DATA_YAML_EXPANDED, "w") as f:
        f.write(content)
    print(f"\n  [OK] Expanded data.yaml: {DATA_YAML_EXPANDED}")

    # Load V1 model and retrain
    if torch.cuda.is_available():
        print(f"\n  GPU: {torch.cuda.get_device_name(0)}")

    print(f"\n  Loading V1 model for fine-tuning: {V1_MODEL}")
    model = YOLO(str(V1_MODEL))

    print(f"\n  Starting retraining on expanded dataset...")
    print("-" * 60)

    model.train(
        data=str(DATA_YAML_EXPANDED),
        epochs=EPOCHS,
        imgsz=IMG_SIZE,
        batch=BATCH_SIZE,
        optimizer=OPTIMIZER,
        lr0=LR0,
        lrf=LRF,
        patience=PATIENCE,
        device=DEVICE,
        workers=WORKERS,
        project=str(OUTPUT_DIR),
        name=RUN_NAME,
        exist_ok=True,
        pretrained=True,
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,
        degrees=10.0,
        translate=0.1,
        scale=0.5,
        flipud=0.2,
        fliplr=0.5,
        mosaic=1.0,
        mixup=0.1,
        weight_decay=0.0005,
        warmup_epochs=3.0,
        box=7.5,
        cls=0.5,
        save=True,
        plots=True,
        verbose=True,
    )

    print("\n" + "=" * 60)
    print("  RETRAIN COMPLETE")
    print("=" * 60)
    best = OUTPUT_DIR / RUN_NAME / "weights" / "best.pt"
    print(f"\n  Best model (V2): {best}")
    print("=" * 60)


if __name__ == "__main__":
    main()
